<?php
require_once "config.php";

if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['codigo'])) {
    $codigo = $_POST['codigo'];
    $perfil = $_POST['perfil'];
    $unidad = $_POST['unidad'];
    $password = $_POST['password'];

    echo actualizarUsuario($codigo, $perfil, $unidad, $password);
}

// Función para obtener datos del funcionario
function obtenerFuncionario($codigo)
{
    $sql = "SELECT 
        FUNCIONARIO.FUN_CODIGO,
        FUNCIONARIO.FUN_RUT,
        FUNCIONARIO.FUN_NOMBRE,
        IFNULL(FUNCIONARIO.FUN_NOMBRE2, '') AS FUN_NOMBRE2,
        FUNCIONARIO.FUN_APELLIDOPATERNO,
        FUNCIONARIO.FUN_APELLIDOMATERNO,
        GRADO.GRA_DESCRIPCION,
        IF(CARGO_FUNCIONARIO.UNI_AGREGADO, CONCAT(CARGO.CAR_DESCRIPCION, ' A ', UNIDAD.UNI_DESCRIPCION), CARGO.CAR_DESCRIPCION) AS CARGO,
        VISTA_ARBOL_UNIDADES_NACIONAL_CON_PREFECTURAS.ZONA_DESCRIPCION,
        VISTA_ARBOL_UNIDADES_NACIONAL_CON_PREFECTURAS.PREFECTURA_DESCRIPCION,
        VISTA_ARBOL_UNIDADES_NACIONAL_CON_PREFECTURAS.COMISARIA_DESCRIPCION,
        VISTA_ARBOL_UNIDADES_NACIONAL_CON_PREFECTURAS.UNI_DESCRIPCION,
        TIPO_USUARIO.TUS_DESCRIPCION,
        IFNULL(CAPACITACION.TIPO_CAPACITACION, 'SIN CURSO') AS CAPACITACION,
        CAPACITACION.NOTA_PROSERVIPOL,
        CAPACITACION.FECHA_CAPACITACION,
        USUARIO.US_LOGIN,
        USUARIO.US_PASSWORD,
        USUARIO.UNI_CODIGO,
        USUARIO.TUS_CODIGO
        FROM CARGO_FUNCIONARIO
        JOIN FUNCIONARIO ON CARGO_FUNCIONARIO.FUN_CODIGO = FUNCIONARIO.FUN_CODIGO
        JOIN GRADO ON FUNCIONARIO.ESC_CODIGO = GRADO.ESC_CODIGO 
            AND FUNCIONARIO.GRA_CODIGO = GRADO.GRA_CODIGO
        JOIN CARGO ON CARGO.CAR_CODIGO = CARGO_FUNCIONARIO.CAR_CODIGO 
            AND CARGO.CAR_CODIGO != 3500
        LEFT JOIN UNIDAD ON UNIDAD.UNI_CODIGO = CARGO_FUNCIONARIO.UNI_AGREGADO
        INNER JOIN USUARIO ON USUARIO.FUN_CODIGO = FUNCIONARIO.FUN_CODIGO
        INNER JOIN TIPO_USUARIO ON TIPO_USUARIO.TUS_CODIGO = USUARIO.TUS_CODIGO
        LEFT JOIN CAPACITACION ON CAPACITACION.FUN_CODIGO = FUNCIONARIO.FUN_CODIGO 
            AND CAPACITACION.ACTIVO = 1
                    JOIN VISTA_ARBOL_UNIDADES_NACIONAL_CON_PREFECTURAS 
            ON USUARIO.UNI_CODIGO = VISTA_ARBOL_UNIDADES_NACIONAL_CON_PREFECTURAS.UNI_CODIGO
        WHERE CARGO_FUNCIONARIO.FECHA_HASTA IS NULL
            AND USUARIO.FUN_CODIGO LIKE '%$codigo%'";
    /*
    $sql = "SELECT 
        FUNCIONARIO.FUN_CODIGO,
        FUNCIONARIO.FUN_RUT,
        FUNCIONARIO.FUN_NOMBRE,
        IFNULL(FUNCIONARIO.FUN_NOMBRE2, '') AS FUN_NOMBRE2,
        FUNCIONARIO.FUN_APELLIDOPATERNO,
        FUNCIONARIO.FUN_APELLIDOMATERNO,
        GRADO.GRA_DESCRIPCION,
        IF(CARGO_FUNCIONARIO.UNI_AGREGADO, CONCAT(CARGO.CAR_DESCRIPCION, ' A ', UNIDAD.UNI_DESCRIPCION), CARGO.CAR_DESCRIPCION) AS CARGO,
        VISTA_ARBOL_UNIDADES_NACIONAL_CON_PREFECTURAS.ZONA_DESCRIPCION,
        VISTA_ARBOL_UNIDADES_NACIONAL_CON_PREFECTURAS.PREFECTURA_DESCRIPCION,
        VISTA_ARBOL_UNIDADES_NACIONAL_CON_PREFECTURAS.COMISARIA_DESCRIPCION,
        VISTA_ARBOL_UNIDADES_NACIONAL_CON_PREFECTURAS.UNI_DESCRIPCION,
        TIPO_USUARIO.TUS_DESCRIPCION,
        IFNULL(CAPACITACION.TIPO_CAPACITACION, 'SIN CURSO') AS CAPACITACION,
        CAPACITACION.NOTA_PROSERVIPOL,
        CAPACITACION.FECHA_CAPACITACION,
        USUARIO.US_LOGIN,
        USUARIO.US_PASSWORD,
        USUARIO.UNI_CODIGO,
        USUARIO.TUS_CODIGO
        FROM CARGO_FUNCIONARIO
        JOIN FUNCIONARIO ON CARGO_FUNCIONARIO.FUN_CODIGO = FUNCIONARIO.FUN_CODIGO
        JOIN GRADO ON FUNCIONARIO.ESC_CODIGO = GRADO.ESC_CODIGO 
            AND FUNCIONARIO.GRA_CODIGO = GRADO.GRA_CODIGO
        JOIN VISTA_ARBOL_UNIDADES_NACIONAL_CON_PREFECTURAS 
            ON CARGO_FUNCIONARIO.UNI_CODIGO = VISTA_ARBOL_UNIDADES_NACIONAL_CON_PREFECTURAS.UNI_CODIGO
        JOIN CARGO ON CARGO.CAR_CODIGO = CARGO_FUNCIONARIO.CAR_CODIGO 
            AND CARGO.CAR_CODIGO != 3500
        LEFT JOIN UNIDAD ON UNIDAD.UNI_CODIGO = CARGO_FUNCIONARIO.UNI_AGREGADO
        INNER JOIN USUARIO ON USUARIO.FUN_CODIGO = FUNCIONARIO.FUN_CODIGO
        INNER JOIN TIPO_USUARIO ON TIPO_USUARIO.TUS_CODIGO = USUARIO.TUS_CODIGO
        LEFT JOIN CAPACITACION ON CAPACITACION.FUN_CODIGO = FUNCIONARIO.FUN_CODIGO 
            AND CAPACITACION.ACTIVO = 1
        WHERE CARGO_FUNCIONARIO.FECHA_HASTA IS NULL
            AND FUNCIONARIO.FUN_CODIGO LIKE '%$codigo%'";*/

    $res = ejecutar($sql);
    return obtener_array($res);
}

// Función para obtener últimos accesos
function obtenerUltimosAccesos($codigo)
{
    $sql = "SELECT 
            BITACORA_USUARIO.US_FECHAHORA_INICIO,
            GRADO.GRA_DESCRIPCION,
            CONCAT_WS(' ', FUNCIONARIO.FUN_APELLIDOPATERNO, FUNCIONARIO.FUN_APELLIDOMATERNO, FUNCIONARIO.FUN_NOMBRE, FUNCIONARIO.FUN_NOMBRE2) AS NOMBRE_COMPLETO,
            FUNCIONARIO.FUN_CODIGO,
            UNIDAD.UNI_DESCRIPCION,
            TIPO_USUARIO.TUS_DESCRIPCION,
            BITACORA_USUARIO.US_DIRECCION_IP
            FROM
            BITACORA_USUARIO
            INNER JOIN UNIDAD ON (BITACORA_USUARIO.UNI_CODIGO = UNIDAD.UNI_CODIGO)
            INNER JOIN USUARIO ON (USUARIO.UNI_CODIGO = UNIDAD.UNI_CODIGO)
            AND (BITACORA_USUARIO.FUN_CODIGO = USUARIO.FUN_CODIGO)
            INNER JOIN TIPO_USUARIO ON (USUARIO.TUS_CODIGO = TIPO_USUARIO.TUS_CODIGO)
            INNER JOIN FUNCIONARIO ON (FUNCIONARIO.FUN_CODIGO = USUARIO.FUN_CODIGO)
            INNER JOIN GRADO ON (FUNCIONARIO.ESC_CODIGO = GRADO.ESC_CODIGO)
            AND (FUNCIONARIO.GRA_CODIGO = GRADO.GRA_CODIGO)
            WHERE
            BITACORA_USUARIO.FUN_CODIGO = '$codigo'
            ORDER BY
            BITACORA_USUARIO.US_FECHAHORA_INICIO DESC
            LIMIT 10";

    return ejecutar($sql);
}

function actualizarUsuario($codigo, $perfil, $unidad, $password)
{
    if ($codigo === '' || $perfil === '' || $unidad === '') {
        return "Faltan datos";
    }

    // Escapar datos
    $codigo = mysql_real_escape_string($codigo);
    $perfil = mysql_real_escape_string($perfil);
    $unidad = mysql_real_escape_string($unidad);
    $password = mysql_real_escape_string($password);

    // Base del UPDATE
    $sql = "UPDATE USUARIO
            SET TUS_CODIGO = '$perfil',
                UNI_CODIGO = '$unidad'";

    // Si el password viene vacío, no se actualiza
    if ($password !== '') {
        $sql .= ", US_PASSWORD = '$password'";
    }

    $sql .= " WHERE FUN_CODIGO = '$codigo'";

    $res = mysql_query($sql);

    if (!$res) {
        return "Error al actualizar: " . mysql_error();
    }

    if (mysql_affected_rows() > 0) {
        return "Datos actualizados correctamente";
    } else {
        return "No se realizaron cambios";
    }
}
